### ISSUE TITLE
Fullscreen is scaled unnecessarily

### ISSUE THREAD

**Issue by xordspar0** [virt-manager/virt-manager#165] opened 2020-10-14 03:57 UTC
**Distro**: Arch Linux
**Version**: 2.2.1 and latest git commit (b17914591aeefedd50a0a0634f479222a7ff591c)

**What I expected to happen**:

My monitor's resolution is 1360x768. I want to run a SPICE graphical console with the guest fullscreen. I expect to be able to set the guest's display resolution to my monitor's resolution and see the guest's display fill my monitor as if it's the bare-metal OS.

**What happened**:

1. When I set my guest's display resolution to 1360x768, virt-manager scales the output and shows it window boxed with black bars on all 4 sides. This is with the scale setting "only when fullscreen".
2. When I keep the guest's resolution at 1360x768 but change the scale setting to never, the display is offset to the right with a ~10 pixel black bar on the left and the guest's display being cut off on the right side.
3. When I set the guest's resolution down to the next lowest setting, 1280x768, then the display is not scaled, but this smaller setting does not fill my wider monitor on the left and right.

I tried this with virt-viewer and I could not reproduce the issue.

I've included screenshots below. The first screenshot shows the guest in fullscreen with the display scaled even though the resolution fits in my monitor. The second screenshot shows the same situation but with scaling turned off; note the black bar on the left side of the screen. The third screenshot is in windowed mode with scaling disabled. You can see the black bar on the left side of the window.

![Screenshot from 2020-10-13 22-54-58](https://user-images.githubusercontent.com/2390950/95941778-26684800-0da7-11eb-8f3c-91e3d9ad45f3.png)

![Screenshot from 2020-10-13 22-54-25](https://user-images.githubusercontent.com/2390950/95941751-13ee0e80-0da7-11eb-89db-be945385f124.png)

![Screenshot from 2020-10-13 22-39-20](https://user-images.githubusercontent.com/2390950/95940989-4d257f00-0da5-11eb-87ce-f9e698b60746.png)

**Comment by crobinso** [comment] 2020-10-14 13:47
Thanks for the detailed report. Can you check if this reproduces with virt-manager v2.2.1 (git checkout v2.2.1). That will be a useful data point to know if virt-manager regressed here in the last release, which was a big one.

If v2.2.1 does *not* have the issue, can you try a git bisect:

```console
$ git bisect good v2.2.1
$ git bisect bad master
# ... reproduce the issue. if it worked, do
$ git bisect good
# ... if it didn't work, do:
$ git bisect bad
# Eventually it will tell you the offending commit
```

**Comment by xordspar0** [comment] 2020-10-14 13:51
Version 2.2.1 does have the issue. I'll try to find a version that doesn't have it.

**Comment by xordspar0** [comment] 2020-10-14 14:24
I can reproduce this going back to 2.0.0. Versions older than 2.0 require Python 2, which makes testing those more versions more difficult.

**Comment by crobinso** [comment] 2020-10-14 14:33
Thanks for checking. When I find time I will try to reproduce.

**Comment by xordspar0** [comment] 2020-10-15 00:37
Other observations (all with scaling turned off):

* At 640x480, when I shrink the window to less than 640x480 the display is flush with left side of the screen, but there is a gap on top similar to the gap on the left I see with 1366x768.
* At 1152x768 and 1280x768, when I shrink the window to less than 1152x768 the display is flush with the top and left sides of the screen. :ok_hand:
* At 1360x768 and 1366x768, there is a gap on the left side. 
* At 1600x900, there is a gap at the top.
* At 1920x1080, the display is flush with the top and left sides of the screen (though it goes off the right and bottom sides because my monitor is too small).

**Comment by crobinso** [comment] 2020-10-15 12:53
Thanks for the info.  A couple things you could try to find more info:
* Stop VM, switch to VNC graphics, see if that makes a difference
* Try a different video device like virtio or vga

Also you could try this patch to print some info to the command line. Make sure the numbers there match your VM resolution. If they don't, it's probably a bug in some other component:

```patch
diff --git a/virtManager/details/viewers.py b/virtManager/details/viewers.py
index 8581dbf2..5c7f8470 100644
--- a/virtManager/details/viewers.py
+++ b/virtManager/details/viewers.py
@@ -227,6 +227,7 @@ class Viewer(vmmGObject):
 
     def console_get_desktop_resolution(self):
         ret = self._get_desktop_resolution()
+        print("RESOLUTION: %s" % ret)
         if not ret:
             return ret  # pragma: no cover
```

I will try a VM with that resolution later today

**Comment by xordspar0** [comment] 2020-10-15 14:01
* I can't reproduce it with VNC, only SPICE.
* I also can't reproduce with SPICE and a virtio or VGA video device, only QXL.
* When I printed out the resolution, it said `RESOLUTION: (1408, 768)` when I had the resolution set to 1360x768.

So in summary, I can only reproduce this with SPICE, QXL, and certain resolutions.

Your hunch was right about all three! Excellent deduction, Sherlock.

**Comment by crobinso** [comment] 2020-10-15 15:30
I can reproduce with a fedora 32 VM. I checked virt-viewer code but it reports the correct resolution. It appears virt-manager is using the wrong values from spice for VM resolution. I don't know why our method works for some cases but is wrong for others.

We need to hook into `notify::monitors` like here: https://gitlab.com/virt-viewer/virt-viewer/-/blob/master/src/virt-viewer-session-spice.c#L1217

Which is handled by this callback: https://gitlab.com/virt-viewer/virt-viewer/-/blob/master/src/virt-viewer-session-spice.c#L898

**Comment by crobinso** [comment] 2020-10-21 14:30
We can't duplicate the virt-viewer logic in virt-manager because parts of the spice-gtk python bindings are broken: https://gitlab.freedesktop.org/spice/spice-gtk/-/issues/132

I filed a spice-gtk bug about the resolution mismatch issue to get more advice, it's possible it's just a plain old bug on their side: https://gitlab.freedesktop.org/spice/spice-gtk/-/issues/133

**Comment by xordspar0** [comment] 2020-10-21 14:55
Awesome, thanks for working on this.

**Comment by crobinso** [comment] 2021-05-24 19:38
Unfortunately there's been no movement on spice side. This appears to still be valid on fedora 34 too. But we are going to be using virtio video model more as the default in the future so this bug may kinda go away with that.

I'm closing this for now. If there's any movement on the spice issues that require virt-manager work, we can revisit this

**Closed by crobinso** 2021-05-24 19:38 UTC
Labels: blocked, bug
