### ISSUE TITLE
Disabling Link state for NIC does not work for Windows guest with e1000e driver

### ISSUE THREAD

**Issue by exploide** [virt-manager/virt-manager#66] opened 2019-12-04 18:49 UTC
I wanted to try the useful "Link state" feature for NICs, in order to temporarily disable network connectivity.

While this works fine for a Linux guest with a virtio driver, it has no effect for a Windows guest with e1000e driver. The XML changes accordingly, but once booted, the system has regular network connectivity.

```xml
<interface type="network">
  <mac address="52:54:00:70:d1:13"/>
  <source network="default"/>
  <model type="e1000e"/>
  <link state="down"/>
  <address type="pci" domain="0x0000" bus="0x01" slot="0x00" function="0x0"/>
</interface>
```

Fedora 31
virt-manager-2.2.1
QEMU emulator version 4.1.1

**Comment by crobinso** [comment] 2019-12-17 20:49
I reproduced, but I don't think this is virt-manager's fault. Like you say, it works correctly with virtio + linux, but even linux + e1000e doesn't correctly detect link change. It does seem to obstruct network usage, so something is happening, but the OS is not detecting link change.

This makes me think it's something on the qemu e1000e implementation side. And googling gives me this, which seems to confirm it: https://bugzilla.redhat.com/show_bug.cgi?id=1707646

That bug was closed because it isn't planned to be fixed for Red Hat's product, but the issue is still probably valid for qemu upstream. You could try filing a bug there: https://www.qemu.org/contribute/report-a-bug/

However i'm closing this issue, because there doesn't appear to be a bug on the virt-manager side

**Closed by crobinso** 2019-12-17 20:49 UTC

**Comment by exploide** [comment] 2019-12-22 10:15
You are right, sorry for falsely opening this issue here.

I opened a bug report at https://bugs.launchpad.net/qemu/+bug/1857226
