### ISSUE TITLE
[Reopen] Need help for compilation under Mint #96

### ISSUE THREAD

**Issue by dexter74** [virt-manager/virt-manager#97] opened 2020-04-09 17:29 UTC
Hello,
Following the closing of the topic (https://github.com/virt-manager/virt-manager/issues/96#event-3217801802), I reopen one because I have always had no answer to compile with the latest version under Mint and it's a problem for me in the workplace.

**Comment by crobinso** [comment] 2020-04-09 22:17
I expected us to still discuss in the closed issue? Closing it doesn't change our ability to discuss. We keep issues open if it is tracking something that will change in the code, this is more like a support question.

**Comment by Antique** [comment] 2020-04-10 11:02
Hi, the generic installation steps are described here https://github.com/virt-manager/virt-manager/blob/master/INSTALL.md . As Cole already wrote you can run virt-manager directly from the git repository as there is no need to compile anything, virt-manager is project written in python.

If you just want to install newer version of virt-manager look for already existing packages for ubuntu, you don't have to learn how to build debian packages and you can just enjoy the newer versions. Ubuntu packages are here https://packages.ubuntu.com/search?keywords=virt-manager .

If by compilation you mean creating a new package out of git repository that is out of scope of any upstream project. It's a job for package maintainer of each distribution and it usually requires knowledge of that specific distribution and the package manager and so on. Since linux mint is ubuntu based distribution and they are using ubuntu packages directly here you can learn about the generic process of creating ubuntu packages https://packaging.ubuntu.com/html/ , as you can see it's not that trivial.

You can also check how the current virt-manager package is created looking at the debian gitlab instance https://salsa.debian.org/libvirt-team/virt-manager where they keep all extra files for debian packages in the `debian` directory.

I'll close the issue as well because there is no issue. Please do not open any new issues for this topic as the conversation can continue here even if the issue is closed.

**Closed by Antique** 2020-04-10 11:02 UTC
