### ISSUE TITLE
Screen misplacement after moving to another monitor in full screen

### ISSUE THREAD

**Issue by tstdin** [virt-manager/virt-manager#605] opened 2023-11-22 10:57 UTC
**Distro**: Fedora 39

After installing Fedora 39, I found out that there is a rendering issue when I move the window which is in full screen mode to another monitor. The screen gets shifted so that only quarter of it is visible at the bottom right corner, the rest is black:

 [Screencast from 2023-11-22 11-19-52.webm](https://github.com/virt-manager/virt-manager/assets/25065143/2da1d0e3-87ee-48dd-8aa3-ada5659e0490)

Reproducible every time, but only if the screen is in full screen mode. Otherwise it does not happen. Also tested on multiple VMs (both Windows and Linux).
It can be fixed by clicking the button to leave the full screen mode - that one is also shifted from the middle to the right edge of the screen.

My screen setup is as follows (notebook at the bottom and two external monitors):
![image](https://github.com/virt-manager/virt-manager/assets/25065143/a07d2b1c-e4fb-4009-a0d1-0e236776da0e)

PS: I am not sure in which component the issue lies, so apology if that is not the virt-manager.

**Comment by crobinso** [comment] 2024-02-27 20:54
Thanks for the report. I can't reproduce on f39 but I'm running on X11. Are you on wayland?

Do other fullscreen apps have the same problem? Like a media player, or evince, or firefox.

Does `virt-viewer` have the same issue?

**Comment by tstdin** [comment] 2024-03-01 20:50
I don't have the exact same setup anymore, but it seems to me like the problem has been fixed. (Yes, I am using wayland)

**Comment by crobinso** [comment] 2024-03-02 15:50
Thanks for following up, I'll close this

**Closed by crobinso** 2024-03-02 15:50 UTC
Labels: bug

**Comment by aronjanosch** [comment] 2025-01-23 20:26
I have a similar issue. And its due to scaling. I set my second monitor to 150% and move the virtmanager window to the second screen, then the screen misplaces and is not usable. If both are at 100% there is no issue at all. 

Guest OS is Kali, with XFCE
