### ISSUE TITLE
changing from Q35 to I440FX, VM fails to start: must be model='pci-root' for this machine type, but model='pcie-root' was found instead

### ISSUE THREAD

**Issue by solomongrundy6** [virt-manager/virt-manager#398] opened 2022-05-28 13:52 UTC
**Distro**: Solus 4.3

I recently tried creating a new virtual machine but was given no option during creation to choose the chipset.  If I let it go to the configuration and change it there, I get the expected errors about the PCI root, etc.  Is this a bug, or is there a different way to create a VM with i440fx chipset now?  Apologies in advance if there's some option or something I'm not seeing.

**Comment by mmaFR** [comment] 2022-06-08 20:32
This setting seems to be available only at VM creation time.

**Comment by crobinso** [comment] 2022-06-13 18:49
On the last page of the New VM wizard, there's a checkbox 'Customize before install`. Select it and continue. You should see the option on the Overview page of the window it pops up. If you don't see it there, reopen this and attach full `virt-manager --debug` output when reproducing

**Comment by solomongrundy6** [comment] 2022-06-17 23:04
It's in the overview panel, yes, but if I change it there I get errors about PCI root and the VM won't start.  If I remember correctly it used to ask before that, during the setup wizard, and would set up the VM accordingly.  Now I can't figure out a way to do that.

**Comment by crobinso** [comment] 2022-06-18 18:03
@solomongrundy6 Please provide full `virt-manager --debug` output when reproducing. I missed the bit about PCI root errors, that sounds like a bug somewhere

**Comment by solomongrundy6** [comment] 2022-06-18 19:04
I don't think the PCI root errors themselves are a bug, that is the expected result when changing a VM from Q35 to i440fx - the problem is that the vm creation wizard sets up PCIe root thinking it's going to be a Q35 VM (the default) and there's no option to have it set up i440fx from the wizard, nor a way (that I can see short of editing the XML directly) to have it change the PCI root set up to a different model.

Debug output can be found here:
https://pastebin.com/aEPMyCk2

**Comment by crobinso** [comment] 2022-06-18 19:28
Ahh thanks I understand now.

You select win10, so virt-manager defaults to q35. When you enter the 'Customize' wizard, we pre-populate the XML with a bunch of pcie controller bits, to enable PCIe hotplug on q35. You are trying to switch back to machine=pc, but then libvirt says 'hey all those pcie bits in the XML aren't valid for machine=pc'. Yes that's a bug in virt-manager

You can work around this by deleting all the `<controller type='pci*` bits in the XML first, with the `XML` editor tab, and then change q35 to pc. But yeah virt-manager needs to be fixed too

**Comment by mniehren** [comment] 2022-07-21 08:42
One more workaround for the installation wizard:
- Chose Win3.1 as System, so the wizard set the system type to i440fx with no pcie Controller

@crobinso It would also be an Option to delete the PCIe-Controller in the Wizard. Currently this is disabled

**Comment by darazi** [comment] 2023-01-22 03:48
I am running into the same error:
"libvirt.libvirtError: XML error: The PCI controller with index='0' must be model='pci-root' for this machine type, but model='pcie-root' was found instead"

I am running Ubuntu 22.04 with VT-D enabled on the BIOS. Attempting to install Home Assistant on KVM. 
Attached is the log file. 

I am pretty new to linux, any ideas would be greatly appreciated. 

[Virt_Log.txt](https://github.com/virt-manager/virt-manager/files/10473684/Virt_Log.txt)

**Comment by agowa** [comment] 2024-06-22 14:39
There is another related error. I tried adding a pci-root **and** pcie-root controller and this results in this error message `pci-root and pcie-root controllers should have index 0`, however setting both to index 0 is not allowed either.

```
Error changing VM configuration: XML error: pci-root and pcie-root controllers should have index 0

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/addhardware.py", line 345, in change_config_helper
    define_func(**define_args)
  File "/usr/share/virt-manager/virtManager/details/details.py", line 1353, in change_cb
    return self.vm.define_xml(newxml)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 347, in define_xml
    self._redefine_xml_internal(origxml, newxml)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 374, in _redefine_xml_internal
    self._define(newxml)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1137, in _define
    self.conn.define_domain(xml)
  File "/usr/share/virt-manager/virtManager/connection.py", line 554, in define_domain
    return self._backend.defineXML(xml)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libvirt.py", line 4559, in defineXML
    raise libvirtError('virDomainDefineXML() failed')
libvirt.libvirtError: XML error: pci-root and pcie-root controllers should have index 0
```

**Comment by phrdina** [comment] 2024-06-24 06:46
> There is another related error. I tried adding a pci-root **and** pcie-root controller and this results in this error message `pci-root and pcie-root controllers should have index 0`, however setting both to index 0 is not allowed either.
> 
> ```
> Error changing VM configuration: XML error: pci-root and pcie-root controllers should have index 0
> 
> Traceback (most recent call last):
>   File "/usr/share/virt-manager/virtManager/addhardware.py", line 345, in change_config_helper
>     define_func(**define_args)
>   File "/usr/share/virt-manager/virtManager/details/details.py", line 1353, in change_cb
>     return self.vm.define_xml(newxml)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 347, in define_xml
>     self._redefine_xml_internal(origxml, newxml)
>   File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 374, in _redefine_xml_internal
>     self._define(newxml)
>   File "/usr/share/virt-manager/virtManager/object/domain.py", line 1137, in _define
>     self.conn.define_domain(xml)
>   File "/usr/share/virt-manager/virtManager/connection.py", line 554, in define_domain
>     return self._backend.defineXML(xml)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/libvirt.py", line 4559, in defineXML
>     raise libvirtError('virDomainDefineXML() failed')
> libvirt.libvirtError: XML error: pci-root and pcie-root controllers should have index 0
> ```

Hi @agowa, that's correct behavior. You cannot have PCI root and PCIe root controller at the same time, there can be only one root controller.

**Comment by agowa** [comment] 2024-06-25 11:01
@phrdina I already discovered that. However that error message probably should be reworded as it implies both can coexist and both should be index=0...

**Comment by phrdina** [comment] 2024-06-25 11:13
> @phrdina I already discovered that. However that error message probably should be reworded as it implies both can coexist and both should be index=0... The message "pci-root and pcie-root controllers should have index 0" is just misleading...

That error message is from libvirt project so nothing we can do about it in virt-manager. You can create a new issue https://gitlab.com/libvirt/libvirt/-/issues to track it there.

**Comment by crobinso** [comment] 2024-09-11 18:44
This issue is fixed in git now, release coming soon

**Closed by crobinso** 2024-09-11 18:44 UTC
Labels: bug
