### ISSUE TITLE
Constructive critisism from daily user with hundreds of VM installations.

### ISSUE THREAD

**Issue by xekon** [virt-manager/virt-manager#158] opened 2020-09-21 00:32 UTC
First, I read over DESIGN.md twice and I do not believe my ideas were covered there, but I apologize if they were and I did not realize they fell under one of those categories/features listed.

**Distro**: Ubuntu 20.04 with plasma-desktop

My primary use is VMs configured to use GPU passthrough.

I am wondering how this feature works, if I use a stock windows iso of windows 10 then it seems to detect it correctly, but if I use a modified iso where I have integrated or removed features then it is no longer detected correctly, how does this feature work? is there any chance this feature could also check the isos label? I generally make the label on my windows 10 isos either "win10" or "windows 10" (I understand I can uncheck the box and accomplish it manually, just hoping there is a way I can make the automatic detect work to save time when creating new vms)
![2020-09-20_16-54](https://user-images.githubusercontent.com/106644/93725449-2c7e5680-fb64-11ea-97fc-df0a2655766c.png)

when creating a new virtual machine with an iso file it is loaded to the cdrom device, but the cdrom device does not get selected from the boot order and moved to the top, this could save some time when creating new vms:
![2020-09-17_22-18](https://user-images.githubusercontent.com/106644/93725405-e1fcda00-fb63-11ea-9b13-69cef5c1594f.png)

maybe add cpu topology to step 3 of 5, otherwise win10 is limited to 2 cpu and it does it as two seperate single core cpus.
with topology right on this page i could set it to 1 cpu 8 core without having to do it on the "customize configuration before installing" page (I understand this exposes a more advanced feature, so I can understand if you declined this, however I think most people, even novices would understand these settings and appreciate them being on this page.):
![2020-09-20_17-13](https://user-images.githubusercontent.com/106644/93725529-db229700-fb64-11ea-824d-3a3f46c938c7.png)

When choosing "Add Hardware" I goto "PCI Host Device" and I add one of my graphics cards and the onboard audio and passthrough those to the vm, would be nice if I could hold down control and select all 3 of these:
![2020-09-17_16-21](https://user-images.githubusercontent.com/106644/93725604-6308a100-fb65-11ea-886f-17fe0ff585fe.png)

similarly to the previous one I add two "USB Host Device" both keyboard and mouse would be nice to be able to hold control and add them both:
![2020-09-20_17-21](https://user-images.githubusercontent.com/106644/93725660-c1ce1a80-fb65-11ea-8298-6fc2b4d4c54d.png)

when adding devices that are already in use by another VM, there is a popup that shows, it would be really nice if that popup had a checkbox that said "Never show hardware already assigned popup again", each time I create a passthrough VM I add these same 5 devices to each and ever VM, so I have to close this popup 5 times per VM, when testing custom iso I might blow the vm away and reinstall it 30+ times, so I would really appreciate this one for sure and I think its a reasonable request.
![2020-09-17_13-09](https://user-images.githubusercontent.com/106644/93725667-d3afbd80-fb65-11ea-8271-8c0ec3792463.png)

There is one more Feature request if you will, but its probably more difficult to implement, and likely wont be a high priority, I have no idea how you might even accomplish it. Every time I create a passthrough VM I remove several devices, I am wondering if there might be a way to accomplish this faster, such as a custom default or a quick remove option... I really have no idea. but every time I create a passthrough VM I remove all these devices.

There is ONE idea I can think of that would make this slightly faster, If you could place "Controller USB 0" either above "Tablet" or below the two "USB Redirector" devices, then I can mash the "- Remove" button quicker.

Currently I have to select "Tablet" from the list on the left then I mash the "- Remove" button until it gets down to "Controller USB 0" at that point I have to left click again on "USB Redirector 1" and I can mash the "- Remove" button two more times. if the "Controller USB 0" were moved above "Tablet" or below the two "USB Redirectors" then I could mash the "- Remove" button in one fell swoop:
![2020-09-20_17-31](https://user-images.githubusercontent.com/106644/93725840-16be6080-fb67-11ea-8d7b-d0608e9f32e6.png)

I hope really some of this feedback is useful. I absolutely love using Virtual Machine Manager and only wish to see it continue to improve :)

**Comment by Toolybird** [comment] 2020-09-21 04:49
> if I use a stock windows iso of windows 10 then it seems to detect it correctly, but if I use a modified iso
> where I have integrated or removed features then it is no longer detected correctly, how does this feature work?

I'm not the dev but I think I can answer this one. The detection works on info provided by libosinfo, specifically osinfo-db. If you run `file' on the stock iso you will see an embedded file system label. eg:
```
$ file en_windows_10_consumer_editions_version_2004_updated_may_2020_x64_dvd_36d61c40.iso
en_windows_10_consumer_editions_version_2004_updated_may_2020_x64_dvd_36d61c40.iso: ISO 9660 CD-ROM filesystem data 'CCCOMA_X64FRE_EN-US_DV9' (bootable)
```
That bit starting with "CCC..." is what's used for comparison. Osinfo-db contains a bunch of regexes which match the various iso labels. Therefore all you need to do is create your modified iso with the same label.

I also have another minor issue surrounding new VM UI and os detection but I'll file that one separately.

**Comment by Toolybird** [comment] 2020-09-21 06:55
> Every time I create a passthrough VM I remove several devices, I am wondering if there might be a way
> to accomplish this faster, such as a custom default

BTW, a lot of what you're proposing can be achieved much more efficiently via the command line. virsh is very powerful. virt-install is also worth mastering. I do this kind of thing all the time. For example, you could simply create a "template" VM in the GUI then use that as the basis for all your VM's.

$ virsh dumpxml win10 > win10-template.xml

Every time you need a new VM, just cp the template file to say win10-new.xml, edit the <name> field in the xml then:

$ virsh define win10-new.xml --validate

The new VM is then immediately available in the GUI for you to do whatever with.

**Comment by xekon** [comment] 2020-09-21 18:00
Thanks for the tips, also I am not sure that all it looks like is the embedded system label, I also tried setting mine to 'CCCOMA_X64FRE_EN-US_DV9' with ntlite, and it is still not detected correctly even though it matches:
![2020-09-21_10-57](https://user-images.githubusercontent.com/106644/93803360-9432b100-fbf9-11ea-963d-c2a175057f4d.png)

**Comment by xekon** [comment] 2020-09-21 18:36
@Toolybird there must be more to it than the volume id, they are the same and still not detected on the image I modified, only the original untouched one:
![2020-09-21_11-34](https://user-images.githubusercontent.com/106644/93806855-a7944b00-fbfe-11ea-938a-2a4d1949e1bd.png)

**Comment by phrdina** [comment] 2020-09-21 20:39
In order to check if your ISO will work you can use `osinfo-detect /path/to/your.iso` to see if libosinfo matches it to the osinfo-db.

If you look into the outputs there is an extra section `Eltorito validation header` in the original ISO and it has some boot related data. If I run `osinfo-detect` on original windows ISO it says `Media is bootable.` and looking at the osinfo code if the media is not bootable it will not try any detection.

**Comment by xekon** [comment] 2020-09-21 20:54
@phrdina you are correct, osinfo-detect says the media is not bootable, but it absolutely IS bootable, so I guess the issue lies with osinfo-detect thinking that the media is not bootable. Thanks.

**Comment by Toolybird** [comment] 2020-09-21 22:23
> there must be more to it than the volume id

Well, all I can say is it worked last time I tried. BTW, I notice your Volume id's don't match exactly.

I also took care to try and recreate the iso as close as possible to the original. Therefore I used MS tools (oscdimg?) and figured out how to make it bootable under both BIOS and UEFI. Starting to get offtopic here though...

**Comment by crobinso** [comment] 2020-09-21 22:50
For a lot of this I agree with @Toolybird. If you are regularly creating the same VM config with lots of similar modifications, you should definitely look into virt-install and/or virt-xml, or XML templating.

There's a lot of options and it may seem daunting at first but from what you describe it sounds like you want something close to:

```
virt-install \
    --print-xml --dry-run \
    --name win10 \
    --os-variant win10 \
    --cdrom ISO \
    --memory 4096 \
    --vcpus 2 --cpu topology.cores=2 \
    --disk size=40 \
    --graphics none --controller type=usb,model=none --sound none \
    --hostdev <lspci output> \
    --hostdev <lsusb output> \
    ...
```

Drop the first line to actually run the config. I guess if you are performing an install you will not want to use '--graphics none'. But you can remove the devices afterwards with `virt-xml`. Example `virt-xml VMNAME --edit --remove-device --graphics 1` for example. You can add it all to a bash script to simplify it.

For your specific issues
* ISO detection: already kinda covered above
* CDROM boot order: I can't reproduce. Do you mean via the last page of 'New VM' wizard, select 'Customize', it doesn't show CDROM as bootable? This is because the the customize wizard shows the post-install VM config for editing, and we only set the CDROM as the boot device for one boot, to perform the install, and then set to boot from the disk device afterwards.
* The PCI/USB multi select option: yes this is a case for virt-install, or virt-xml commands in a script. Write it once and it will save you a lot of clicking. Multi select options don't fit the libvirt APIs here very well, if an attach fails we would leave the VM in a mixed configured state, we have to communicate that to the user, or attempt to unwind the half finished commands etc. It would complicate things on our side and this is definitely all falling under advanced user territory IMO.
* PCI/USB device collisions, same logic mostly. I'm not opposed to adding a 'skip' option here, but if you see this enough that it is painful for you, it's a sign that there's a better tool for the job than clicking in the UI.
* Device removal stuff, kinda similar. But even without using virt-install you could do this a lot quicker with the XML editor. Overview->XML, learn the XML that is representing the devices you want to delete, and do it manually. Devices are pretty clearly named in the XML it shouldn't be too hard.

**Comment by xekon** [comment] 2020-09-21 23:37
thanks guys, i will make use of the xml template to speed things up. I am already familiar with virsh edit because i have to edit the config or my nvidia gpu will not work properly (nvidia tries to block virtualization)

I created the iso with NTLite and I found out the reason it did not work is because they changed "EN-US" to "EN_US" so I made a post on their support forum asking if they could allow "-" character instead of replacing it with "_" in iso labels.

I still hope some of my feedback is helpful, it sounds like the only one you might add is the checkbox to skip the popup when a device is already in use on another VM.

I hope you will also consider adding the cpu topology to step 3 of 5.

I did not realize that adding mutliple pci or usb items could cause that much of an issue, that is really unfortunate, I am used to holding control and selecting multiple things in most programs I use.

Appreciate the responses, going to try using xml templates today :)

**Comment by xekon** [comment] 2020-09-22 01:57
so I created a windows 10 VM.

next I copied the config
$ virsh dumpxml win10 > win10.xml

after that I deleted the existing win10 VM in virt-manager

next I tried to recreate the VM:
$ virsh define win10.xml --validate

It recreated the VM, however it cannot be started because "/var/lib/libvirt/images/win10.qcow2" does not exist

is there a way I can edit the XML file so that its in a create new vm state? so that when I use this template it creates the .qcow2 for me similar to how the GUI does.

**Comment by crobinso** [comment] 2020-09-22 16:00
re: cpu topology, sorry I forgot to mention that. There's an open issue here tracking changing topology to use cores by default, at least for windows. So the plan is to make this 'just work' for what you want: https://github.com/virt-manager/virt-manager/issues/155

It sounds like the rest of the bits have been addressed so I'll close this. Thanks for the suggestions

**Closed by crobinso** 2020-09-22 16:00 UTC
