### ISSUE TITLE
Virtual Machine Manager: failed to start, internal error: unable to find audio backend for sound device

### ISSUE THREAD

**Issue by mswal2846** [virt-manager/virt-manager#324] opened 2021-11-06 14:51 UTC
**Fedora 35**: 

I had setup three VMs under the Virtual Machine Manager: 1 Linux, Windows 10 and Windows 11. All three worked fine. Then I upgraded to Fedora 35. Now the Linux and Windows 10 systems are fine, but Windows 11 give me this error when I attempt to start it:

    failed to start
    internal error: unable to find audio backend for sound device

The details are:

    Error starting domain: internal error: unable to find audio backend for sound device

    Traceback (most recent call last):
    File "/usr/share/virt-manager/virtManager/asyncjob.py", line 65, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
    File "/usr/share/virt-manager/virtManager/asyncjob.py", line 101, in tmpcb
    callback(*args, **kwargs)
    File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
    File "/usr/share/virt-manager/virtManager/object/domain.py", line 1329, in startup
    self._backend.create()
    File "/usr/lib64/python3.10/site-packages/libvirt.py", line 1353, in create
    raise libvirtError('virDomainCreate() failed')
    libvirt.libvirtError: internal error: unable to find audio backend for sound device

In attempting to search for solutions, there isn't an exact match to the error but it's curious it's just with the Windows 11 VM and the others are fine.

Any ideas?

**Comment by smitterl** [comment] 2021-11-26 11:15
@mswal2846 

Libvirt recently - v7.2 - added a new element. As you mention VNC and audio error, this looks related.

IIUC, the audio element none is added per default now. ref https://libvirt.org/formatdomain.html#none-audio-backend

From https://libvirt.org/formatdomain.html#graphical-framebuffers:

> A VNC server could be optionally mapped to the specific host audio backend using the <audio> sub-element:
>
> &lt; graphics type='vnc' ...&gt;
>   &lt;audio id='1'&gt;
> &lt;/graphics&gt;
> Where 1 is an id of the audio device. If no ID is specified, then the default audio backend will be used. Since 7.2.0, qemu.

**Comment by crobinso** [comment] 2021-12-14 18:26
Thanks for the report. If just updating Fedora broke this, it's probably an issue with libvirt update. Could be due to some previous XML virt-manager added that then a new libvirt had issue with. But virt-manager doesn't explicitly set any `<audio>` XML so I'm not sure it's at fault.

I'm closing this for now, but if you reproduce, please reopen and attach `~/.cache/virt-manager/virt-manager.log`

**Closed by crobinso** 2021-12-14 18:26 UTC
