### ISSUE TITLE
virt-manager can no longer shut down/reboot recent Windows 10 Pro

### ISSUE THREAD

**Issue by jefferysmall** [virt-manager/virt-manager#271] opened 2021-07-07 19:05 UTC
Xubuntu 20.04 fully patched
virt-manager 1:2.2.1-3ubuntu2.1 package
VM running: Windows 10 Pro, 21H1, OS build 19043.1055

I've been running Windows 10 Pro for years in a VM with few problems.  However, after a recent Windows update, virt-manager does not appear to be able to signal for Windows to either reboot or shutdown.  The light-switch icon does nothing and selecting either operation from the icon's pull-down menu or from the main menu Virtual Machine->Shutdown do nothing.  These command do work from the Windows 10 Start menu button.  I had an older backup copy of Windows 10 Pro (20H2) and virt-manager shuts this down just fine, so some change seems to have been made to the external signaling for Windows 10 between these two Windows 10 Pro versions and virt-manager does not appear to be communicating any longer.

Of course, virt-manager starts the Windows process just fine and Force Off works because there is no signaling required to start/terminate the process.

I hope this is sufficient info to be able to track down the problem.

**Comment by crobinso** [comment] 2021-07-07 23:37
The issue template comment explains that this tracker is for latest virt-manager only. Your version is 2 years old.

This is unlikely to be a virt-manager or libvirt issue, they are doing very little here. If you are triggering ACPI shutdown, it's possible it's qemu or kvm issue but it would take some investigation to figure it out. Could also be a windows regression

Do you know if you have qemu guest agent installed in the VM, like did you use a virtio driver installer at some point? Updating or installing it may get shutdown working again for you, if libvirt detects the guest agent is connected it will try to use that method for inovking shutdown. If you never used it you may need to add a 'channel qemu-ga' device to your VM in virt-manager. https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/virtio-win-guest-tools.exe

If you did have qemu-guest-agent installed, and updating it doesn't work, it may be a qemu-guest-agent bug. See if `sudo virsh shutdown --method agent $VMNAME` works or doesn't work, and compare that with `sudo virsh shutdown --method acpi $VMNAME`. If the agent case is failing, you may want to file a bug with qemu.

I'm closing this issue though because it's unlikely virt-manager, but we can still discuss

**Closed by crobinso** 2021-07-07 23:37 UTC
