### ISSUE TITLE
Failed to establish connection with qemu 8.0.2

### ISSUE THREAD

**Issue by volker-raschek** [virt-manager/virt-manager#534] opened 2023-06-12 07:00 UTC
Hi,
I've upgraded the qemu packages to the latest version - currently 8.0.2. Since the update virt-manager and virsh are not able to establish a local connection.

Distro: Arch Linux
Qemu: 8.0.2 

```text
virt-manager --debug
[Mo, 12 Jun 2023 08:42:39 virt-manager 3237] DEBUG (cli:204) Version 4.1.0 launched with command line: /usr/bin/virt-manager --debug
[Mo, 12 Jun 2023 08:42:39 virt-manager 3237] DEBUG (virtmanager:167) virt-manager version: 4.1.0
[Mo, 12 Jun 2023 08:42:39 virt-manager 3237] DEBUG (virtmanager:168) virtManager import: /usr/share/virt-manager/virtManager
[Mo, 12 Jun 2023 08:42:39 virt-manager 3237] DEBUG (virtmanager:205) PyGObject version: 3.44.1
[Mo, 12 Jun 2023 08:42:39 virt-manager 3237] DEBUG (virtmanager:209) GTK version: 3.24.38
[Mo, 12 Jun 2023 08:42:39 virt-manager 3237] DEBUG (systray:84) Imported AppIndicator3=<IntrospectionModule 'AyatanaAppIndicator3' from '/usr/lib/girepository-1.0/AyatanaAppIndicator3-0.1.typelib'>
[Mo, 12 Jun 2023 08:42:39 virt-manager 3237] DEBUG (systray:90) Using AppIndicator3 for systray
[Mo, 12 Jun 2023 08:42:39 virt-manager 3237] DEBUG (systray:476) Showing systray: True
[Mo, 12 Jun 2023 08:42:39 virt-manager 3237] DEBUG (inspection:206) python guestfs is not installed
[Mo, 12 Jun 2023 08:42:39 virt-manager 3237] DEBUG (engine:113) Loading stored URIs:
lxc:///  
qemu:///system
[Mo, 12 Jun 2023 08:42:39 virt-manager 3237] DEBUG (engine:461) processing cli command uri= show_window=manager domain=
[Mo, 12 Jun 2023 08:42:39 virt-manager 3237] DEBUG (engine:464) No cli action requested, launching default window
[Mo, 12 Jun 2023 08:42:39 virt-manager 3237] DEBUG (manager:185) Showing manager
[Mo, 12 Jun 2023 08:42:39 virt-manager 3237] DEBUG (engine:316) window counter incremented to 1
[Mo, 12 Jun 2023 08:42:39 virt-manager 3237] DEBUG (engine:211) Initial gtkapplication activated
[Mo, 12 Jun 2023 08:42:39 virt-manager 3237] DEBUG (connection:482) conn=qemu:///system changed to state=Verbinden
[Mo, 12 Jun 2023 08:42:39 virt-manager 3237] DEBUG (connection:903) Scheduling background open thread for qemu:///system
^C[Mo, 12 Jun 2023 08:46:42 virt-manager 3237] DEBUG (virtmanager:261) Received KeyboardInterrupt. Exiting application.
[Mo, 12 Jun 2023 08:46:42 virt-manager 3237] DEBUG (connection:838) conn.close() uri=qemu:///system
[Mo, 12 Jun 2023 08:46:42 virt-manager 3237] DEBUG (connection:482) conn=qemu:///system changed to state=Getrennt
[Mo, 12 Jun 2023 08:46:42 virt-manager 3237] DEBUG (manager:196) Closing manager
[Mo, 12 Jun 2023 08:46:42 virt-manager 3237] DEBUG (engine:323) window counter decremented to 0
[Mo, 12 Jun 2023 08:46:42 virt-manager 3237] DEBUG (engine:369) Exiting app normally.
```

I see only in virt-manager that a connection will be established. After 5 min I quit virt-manager and I tried again - same result. I rolled back qemu to prior 7 major versions - virt-manager works now again as expected.

Volker

**Comment by ajgringo619** [comment] 2023-06-12 15:51
I get this as well after nearly every reboot. A restart of the `libvirtd` service works, although I can't find any error(s) as to why this keeps happening. The initial 8.0 `qemu` release did not have this problem.

**Comment by volker-raschek** [comment] 2023-06-13 06:40
Hi @ajgringo619, I can confirm that a restart of `libvirtd` solve temporarily the connection problem after a system reboot.

**Comment by sunwire** [comment] 2023-06-13 13:11
The problem is the latest systemd https://github.com/systemd/systemd/issues/27953
If you downgrade or [patch](https://github.com/systemd/systemd/pull/28000) systemd everything works fine.

**Comment by wcasanova** [comment] 2023-06-14 22:08
Fixes [https://github.com/systemd/systemd/pull/28035](https://github.com/systemd/systemd/pull/28035)

**Comment by biggestsonicfan** [comment] 2023-06-16 01:29
Applied `28035` to the [openSUSE/systemd](https://github.com/openSUSE/systemd) as a patch through [obs](https://build.opensuse.org/package/show/home:biggestsonicfan:branches:Base:System/systemd) but the connection issue persists.

**Comment by biggestsonicfan** [comment] 2023-06-18 20:26
So what does this mean for other distros which use their own systemd, such as [SUSE](https://github.com/openSUSE/systemd). I applied `28035` as a patch to [their live build distribution](https://build.opensuse.org/package/show/Base:System/systemd), and the virt-manager issue persisted. Did `28000` need to be applied as well?

**Comment by crobinso** [comment] 2024-02-27 15:13
Sorry for late response, but yes this was a systemd regression that I suspect is fixed in all distros now, so I'm closing this

**Closed by crobinso** 2024-02-27 15:13 UTC
