### ISSUE TITLE
virt-install uses wrong scratchdir location for remote qemu session URI

### ISSUE THREAD

**Issue by Bob131** [virt-manager/virt-manager#549] opened 2023-08-10 22:21 UTC
**Distro**: Fedora

When running a command like
```
virt-install \
  --connect qemu+ssh://some-user@some-machine/session \
  --name fedora \
  --memory 2048 \
  --disk size=20 \
  --location https://download.fedoraproject.org/pub/fedora/linux/releases/38/Everything/x86_64/os
```
the VM installation fails with an error message about `/var/lib/libvirt/boot` being inaccessible. Running with `--debug` points to the problem:
```
[Fri, 11 Aug 2023 07:41:43 virt-install 47521] DEBUG (urlfetcher:174) hasFile(https://download.fedoraproject.org/pub/fedora/linux/releases/38/Everything/x86_64/os/images/pxeboot/vmlinuz) returning True
[Fri, 11 Aug 2023 07:41:43 virt-install 47521] DEBUG (urlfetcher:174) hasFile(https://download.fedoraproject.org/pub/fedora/linux/releases/38/Everything/x86_64/os/images/pxeboot/initrd.img) returning True
[Fri, 11 Aug 2023 07:41:43 virt-install 47521] DEBUG (urlfetcher:105) Fetching URI: https://download.fedoraproject.org/pub/fedora/linux/releases/38/Everything/x86_64/os/images/pxeboot/vmlinuz
Retrieving 'vmlinuz'                                                                                                                                                                                                   |  11 MB  00:00:00 ... 
[Fri, 11 Aug 2023 07:41:44 virt-install 47521] DEBUG (urlfetcher:190) Saved file to /home/user/.cache/virt-manager/boot/virtinst-cv1_j0gj-vmlinuz
[Fri, 11 Aug 2023 07:41:44 virt-install 47521] DEBUG (urlfetcher:105) Fetching URI: https://download.fedoraproject.org/pub/fedora/linux/releases/38/Everything/x86_64/os/images/pxeboot/initrd.img
Retrieving 'initrd.img'                                                                                                                                                                                                | 102 MB  00:00:08 ... 
[Fri, 11 Aug 2023 07:41:53 virt-install 47521] DEBUG (urlfetcher:190) Saved file to /home/user/.cache/virt-manager/boot/virtinst-g7ixdjni-initrd.img
[Fri, 11 Aug 2023 07:41:53 virt-install 47521] DEBUG (volumeupload:136) Uploading kernel/initrd media
[Fri, 11 Aug 2023 07:41:53 virt-install 47521] DEBUG (volumeupload:27) Building storage pool: path=/var/lib/libvirt/boot name=boot-scratch
[Fri, 11 Aug 2023 07:41:53 virt-install 47521] DEBUG (storage:378) Creating storage pool 'boot-scratch' with xml:
<pool type="dir">
  <name>boot-scratch</name>
  <target>
    <path>/var/lib/libvirt/boot</path>
  </target>
</pool>

[Fri, 11 Aug 2023 07:41:53 virt-install 47521] DEBUG (installertreemedia:285) Removing /home/user/.cache/virt-manager/boot/virtinst-cv1_j0gj-vmlinuz
[Fri, 11 Aug 2023 07:41:53 virt-install 47521] DEBUG (installertreemedia:285) Removing /home/user/.cache/virt-manager/boot/virtinst-g7ixdjni-initrd.img
[Fri, 11 Aug 2023 07:41:53 virt-install 47521] DEBUG (cli:256)   File "/usr/bin/virt-install", line 8, in <module>
    virtinstall.runcli()
  File "/usr/share/virt-manager/virtinst/virtinstall.py", line 1233, in runcli
    sys.exit(main())
  File "/usr/share/virt-manager/virtinst/virtinstall.py", line 1226, in main
    start_install(guest, installer, options)
  File "/usr/share/virt-manager/virtinst/virtinstall.py", line 974, in start_install
    fail(e, do_exit=False)
  File "/usr/share/virt-manager/virtinst/cli.py", line 256, in fail
    log.debug("".join(traceback.format_stack()))

[Fri, 11 Aug 2023 07:41:53 virt-install 47521] ERROR (cli:257) Could not start storage pool: cannot open directory '/var/lib/libvirt/boot': Permission denied
```

It seems like a possible fix would be to use a scratch directory in the remote user's home instead for unprivileged connections. Does this make sense, or is there a reason this isn't done already?

You can see from the traceback that I'm using a distro-packaged  version (4.1.0), but I've confirmed that the behaviour is the same with the current main (7cd6151a212c4c477a947fe5a7f2b3363dd0dcbd).

**Comment by crobinso** [comment] 2024-09-11 09:03
Duplicate of #458

**Closed by crobinso** 2024-09-11 09:03 UTC
Labels: bug
