### ISSUE TITLE
Removing password from VNC/Spice doesn't seem to work

### ISSUE THREAD

**Issue by PenelopeFudd** [virt-manager/virt-manager#532] opened 2023-06-09 21:45 UTC
**Distro**: Fedora 37
**Version**: virt-manager-4.1.0-1.fc37.noarch.rpm

Just found virt-manager today, been testing it for about 15 minutes, and it looks great!

The problem: If you add a "Display Spice" or "Display VNC" with password, then remove the password, virt-viewer keeps asking for a password, even if you shutdown/restart.  The graphics device(s) have to be deleted and recreated to restore access.

* Started virt-manager, connected to the host machine, saw all of my VMs: great!
* Opened one, clicked on "show virtual hardware details"
* Clicked "Add Hardware" > "Graphics" > Type "Spice server" > Password: "asdf" > "Finish"
* Got message "This device could not be attached tot he running machine.  Would you like to make the device available after the next guest shutdown?" > "Yes"
* Clicked "Add Hardware" > "Graphics" > Type "VNC" > Password: "qwer" > "Finish"
* Got message "This device could not be attached to the running machine.  Would you like to make the device available after the next guest shutdown?" > "Yes"
* Clicked "Shutdown"  (this could handle a "please wait" dialog box or something; it feels "hung")
* Clicked on "Show the graphical console" waited for finish
* Clicked on "Power on virtual machine"
* Password: asdf  (the Spice password)
* Click on "show virtual hardware details"
* Click on "Display Spice"
* Delete the password, uncheck the password box, click "Apply"
* Click on "Display VNC"
* Delete the password, uncheck the password box, click "Apply"
* Click on "Shutdown"
* Close the virt-viewer, open the VM again, start VM, asks for a password!  Not expected, and neither 'asdf' nor 'qwer' work.
* Click on "show virtual hardware details" > "Display Spice"  No password set, checkbox is unchecked.
* Click on "Display VNC" No password set, checkbox is unchecked.

To get console access again, I had to delete "Display Spice" and "Display VNC" and shutdown/restart the VM.

Also found that clicking "Reboot" is not the same as shutting down and restarting; the changes aren't applied.  It might help if that point were emphasized in the dialog box, or perhaps an icon or message on the menu bar saying "Pending changes, please shutdown/restart (not reboot) to apply." or similar.

Also lost track of what I'd done and added a second "Display Spice" after the reboot.  When I shutdown/restarted, there were two "Display Spice" devices shown, and the VM wouldn't start because it said you can't have two of them.  :-(  

Maybe have pending devices show up, but disabled (e.g. greyed-out), and pending deletions have a line through them?

Thanks for a great program!  This sure beats editing XML files with a text editor!  :-)

**Comment by crobinso** [comment] 2024-10-08 17:49
Sorry for the late reply. I just tried reproducing with upstream git, but it was all working as expected for me. Are you still seeing this with upstream code?

```
git clone https://github.com/virt-manager/virt-manager
cd virt-manager
./virt-manager --debug
```

**Comment by phrdina** [comment] 2024-11-20 08:27
Closing this issue as it works for me as well. If you manage to reproduce it again please reopen.

**Closed by phrdina** 2024-11-20 08:27 UTC
Labels: bug, gfx, needinfo
