### ISSUE TITLE
virt-manager crashes on Sonoma 14.6.1  Apple M2 Pro

### ISSUE THREAD

**Issue by AliyevH** [virt-manager/virt-manager#725] opened 2024-09-16 12:22 UTC
Installed virt-manager and libvirt on mac os using brew package manager. `virt-manager`  command exits with error:

```virt-manager
➜  ~ objc[2261]: +[NSPlaceholderMutableString initialize] may have been in progress in another thread when fork() was called.
objc[2261]: +[NSPlaceholderMutableString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

**Distro**:

**Comment by crobinso** [comment] 2024-09-16 14:35
Duplicate of #620

**Closed by crobinso** 2024-09-16 14:35 UTC
