### ISSUE TITLE
Ability to use VirtIO-GPU

### ISSUE THREAD

**Issue by ash-ketsup** [virt-manager/virt-manager#777] opened 2024-12-01 18:37 UTC
There is some work on the Venus Vulkan driver for VirtIO-GPU:

https://qemu.readthedocs.io/en/master/system/devices/virtio-gpu.html

https://www.collabora.com/news-and-blog/blog/2021/11/26/venus-on-qemu-enabling-new-virtual-vulkan-driver/

It would be nice to be able to configure it in virt-manager same as it's doing now for OpenGL (virgl).

**Comment by phrdina** [comment] 2024-12-05 12:14
Hi, so based on the sources you've provided and my own research this new feature should be in QEMU 9.2.0 that is still not released. In addition we would need support in libvirt first in order to implement it in virt-manager.

It will take some time but should not be an issue to eventually have it implemented.

**Comment by RushingAlien** [comment] 2024-12-08 07:15
Libvirt issue here: https://gitlab.com/libvirt/libvirt/-/issues/638

**Comment by crobinso** [comment] 2024-12-14 18:35
Duplicate of #362

**Closed by crobinso** 2024-12-14 18:35 UTC
Labels: blocked, RFE CLI, RFE UI
