### ISSUE TITLE
Unable to open "Connection details" under zh_CN.UTF-8 locale

### ISSUE THREAD

**Issue by q234rty** [virt-manager/virt-manager#533] opened 2023-06-10 10:51 UTC
**Distro**: Arch Linux rolling latest

Steps to reproduce:

1. Ensure that zh_CN.UTF-8 locale is available
2. Run `env LANG=zh_CN.UTF-8 virt-manager`
3. Select a virtual machine and try to open "编辑->链接详情" i.e. "Connection details"
4. Observe that no window is opened and the GUI is stuck.

This does not seem to happen with other CJK locales like `ja_JP.UTF-8`.

**Comment by crobinso** [comment] 2024-02-04 21:40
Thanks for the report, this could be due to a bad translation. It's working with virt-manager git though so I assume this was fixed with a translation update. If you can still reproduce, please open a new issue and I'll take a look

**Closed by crobinso** 2024-02-04 21:40 UTC
