### ISSUE TITLE
i440FX Windows 7 machines are incorrectly created with PCI-E root rather than plain PCI

### ISSUE THREAD

**Issue by shodanshok** [virt-manager/virt-manager#444] opened 2022-10-08 12:53 UTC
**Distro**: Ubuntu 22.04 LTS, virt-manager 4.0.0

Windows 7 machines created with the BIOS-based i440FX machine type can not be started (or installed) due to being configured with a PCI-E root, which is not supported by the i440FX chipset. In order to create and start such machines, one has to manually edit the corresponding XML file removing any references to the PCI-E root.

Example:
![screenshot1](https://user-images.githubusercontent.com/13137622/194708531-360fb8fb-6b4b-4122-8b7e-4e82d11853ee.jpg)

See also: https://bugs.launchpad.net/ubuntu/+source/virt-manager/+bug/1982500

**Comment by morecache** [comment] 2023-01-05 11:53
I sent patches to dev mailing list for fixing this issue on Sep 2022, But no response.
Please refer to https://listman.redhat.com/archives/virt-tools-list/2022-September/017639.html

I'm about to repost them via github.

**Comment by cheriimoya** [comment] 2023-01-19 15:55
isn't this a duplicate of #398? there is a workaround in the discussion for now if you cannot or don't want to apply any patches

**Comment by shodanshok** [comment] 2023-01-19 17:19
Yes, I adopted the same (inconvenient) workaround, but a newly created machines should really have the correct hardware definition by default.

**Comment by rokejulianlockhart** [comment] 2023-06-03 17:42
@morecache, have you posted the changes at https://github.com/virt-manager/virt-manager/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc? Or is that what you meant by GitHub?

**Comment by morecache** [comment] 2023-06-05 07:24
> @morecache, have you posted the changes at https://github.com/virt-manager/virt-manager/pulls? Or is that what you meant by "GitHub"?

Yes I have, The PR was posted 5 months ago, no review yet.
Actually, It still can be successfully applied to the current git master without any adaptation.
Please refer to https://github.com/virt-manager/virt-manager/pull/475

**Closed** 2024-02-26 15:57 UTC
