### ISSUE TITLE
virt-manager does not read requirements of non distro qemu

### ISSUE THREAD

**Issue by nicman23** [virt-manager/virt-manager#539] opened 2023-07-04 17:13 UTC
I have installed a newer qemu that my distro (focal) supports on /opt/. I defined the xml and everything works with libvirtd.

However when i try to connect to it with virt-manager it errors with:

```
Error launching details: Host does not support domain type kvm with machine 'pc-q35-7.1' for virtualization type 'hvm' with architecture 'x86_64'
```

that happens even when the VM is already running. remote-viewer also connects fine on its spice port

**Comment by lersek** [comment] 2023-08-26 09:55
@crobinso I've started seeing this exact same issue on RHEL-9.2 very recently. Both `virt-manager-4.1.0-4.el9.noarch` and upstream virt-manager at commit 7cd6151a212c throw this exception. It's inexplicable because it used to work absolutely forever.

**Comment by lersek** [comment] 2023-08-26 10:18
This is definitely a regression in one of: qemu, libvirt, or virt-manager. Previously, I could liberally change the `emulator` element in the domain XML from the RHEL-provided `qemu-kvm` binary to one I compiled myself from upstream qemu, in parallel to changing the machine type accordingly. Previously, both libvirt *and* virt-manager worked well after such an update, but now only libvirt is behaving correctly. With virt-manager, I can still start and shutdown the domain in the summary view, but if I try to open the details view (consoles, details etc) then the above-noted error message is raised. The `virsh capabilities` output indeed does not list the machine types of the custom qemu binary (because the default emulator for the host is the RHEL-provided qemu binary, which has different machine types), but that seems irrelevant: the domain XML already specifies the custom emulator I'd like to use. So the machine type noted in the domain XML should be checked against the particular, specified emulator, not the system default emulator.

**Comment by lersek** [comment] 2023-08-26 10:27
@berrange @crobinso Right, this is a regression; bisection between `v3.0.0` and 7cd6151a212c ("uitests: Drop hotplug work around, f38 libvirt is fixed now", 2023-05-24) fingers commit 05fcc7410eee ("virtinst: fix caching of domain capabilities", 2022-07-27). Here's the bisection log:

~~~
git bisect start
# status: waiting for both good and bad commits
# bad: [7cd6151a212c4c477a947fe5a7f2b3363dd0dcbd] uitests: Drop hotplug work around, f38 libvirt is fixed now
git bisect bad 7cd6151a212c4c477a947fe5a7f2b3363dd0dcbd
# status: waiting for good commit(s), bad commit known
# good: [c7ce770170ab319718548bc4dac041687b1d6328] Prep for release 3.0.0
git bisect good c7ce770170ab319718548bc4dac041687b1d6328
# good: [c3e9db5f3a1935193f8fb5e6a9ef3dcb8332cacd] createvm: Tweaks to new UEFI pref
git bisect good c3e9db5f3a1935193f8fb5e6a9ef3dcb8332cacd
# good: [6ec0774d924679d800ec0e8ff2c6742e289c47c8] Translated using Weblate (Swedish)
git bisect good 6ec0774d924679d800ec0e8ff2c6742e289c47c8
# bad: [adad21fb40be5593adc96623bfeac47078ed74ad] Translated using Weblate (Portuguese (Brazil))
git bisect bad adad21fb40be5593adc96623bfeac47078ed74ad
# bad: [effe274a9be478a21f3f0baf864cf3103a9a8b73] tests: test_urls: Update fedora links
git bisect bad effe274a9be478a21f3f0baf864cf3103a9a8b73
# good: [9da917b8ace8be2f93e4a8f071e65d83b31c1eb7] connection: Add get_libvirt_data_root_dir()
git bisect good 9da917b8ace8be2f93e4a8f071e65d83b31c1eb7
# bad: [aeffa4f7110ae3afe7f43a2ac871bebf1d9f6e14] guest: Check coverage for more of domcaps caching
git bisect bad aeffa4f7110ae3afe7f43a2ac871bebf1d9f6e14
# good: [a4a5c1529a81c5bd5636b4847b03643d97fa3dd3] tests: Fix with latest libvirt
git bisect good a4a5c1529a81c5bd5636b4847b03643d97fa3dd3
# bad: [b5e8e58d747c31af68ae353370cd3c2146fe0113] virtinst: include host capbilities in debug log
git bisect bad b5e8e58d747c31af68ae353370cd3c2146fe0113
# bad: [fec5fd84a7563f6c85455e4307650a893088f6ff] virtinst: include domain capbilities in debug log
git bisect bad fec5fd84a7563f6c85455e4307650a893088f6ff
# bad: [05fcc7410eee0dc90331b49d0a7e7727f362c2e4] virtinst: fix caching of domain capabilities
git bisect bad 05fcc7410eee0dc90331b49d0a7e7727f362c2e4
# first bad commit: [05fcc7410eee0dc90331b49d0a7e7727f362c2e4] virtinst: fix caching of domain capabilities
~~~

**Comment by lersek** [comment] 2023-08-26 10:35
The problem seems to be the following: commit 05fcc7410eee ("virtinst: fix caching of domain capabilities", 2022-07-27) introduced a call to `lookup_capsinfo` into `_compare`, via the new helper method `_compare_machine`, and `lookup_capsinfo` now throws an exception, in the above-described situation:

~~~
Error launching details: Host does not support domain type kvm with machine 'pc-q35-8.1' for virtualization type 'hvm' with architecture 'x86_64'

Traceback (most recent call last):
  File "virtManager/vmwindow.py", line 40, in get_instance
    cls._instances[key] = vmmVMWindow(vm)
  File "virtManager/vmwindow.py", line 83, in __init__
    self._details = vmmDetails(self.vm, self.builder, self.topwin,
  File "virtManager/details/details.py", line 389, in __init__
    self._init_details()
  File "virtManager/details/details.py", line 807, in _init_details
    vmmAddHardware.build_video_combo(self.vm, video_dev)
  File "virtManager/addhardware.py", line 816, in build_video_combo
    default = DeviceVideo.default_model(vm.xmlobj)
  File "virtinst/devices/video.py", line 47, in default_model
    if (guest.lookup_domcaps().supports_video_virtio() and
  File "virtinst/guest.py", line 656, in lookup_domcaps
    if not self._domcaps or not _compare(self._domcaps):
  File "virtinst/guest.py", line 646, in _compare
    if self.os.machine and not _compare_machine(domcaps):
  File "virtinst/guest.py", line 633, in _compare_machine
    capsinfo = self.lookup_capsinfo()
  File "virtinst/guest.py", line 674, in lookup_capsinfo
    self._capsinfo = self.conn.caps.guest_lookup(
  File "virtinst/capabilities.py", line 319, in guest_lookup
    raise ValueError(msg)
ValueError: Host does not support domain type kvm with machine 'pc-q35-8.1' for virtualization type 'hvm' with architecture 'x86_64'
~~~

**Comment by lersek** [comment] 2023-08-26 10:50
Note the following, from commit 05fcc7410eee (partial quote):

~~~
diff --git a/virtinst/guest.py b/virtinst/guest.py
index 3fb9a9565f2c..2d8edbe2a246 100644
--- a/virtinst/guest.py
+++ b/virtinst/guest.py
@@ -618,13 +618,21 @@ class Guest(XMLBuilder):
         return True
 
     def lookup_domcaps(self):
+        def _compare_machine(domcaps):
+            capsinfo = self.lookup_capsinfo()
+            if self.os.machine == domcaps.machine:
+                return True
+            if capsinfo.is_machine_alias(self.os.machine, domcaps.machine):
+                return True
+            return False
+
         # We need to regenerate domcaps cache if any of these values change
         def _compare(domcaps):  # pragma: no cover
             if self.type == "test":
                 # Test driver doesn't support domcaps. We kinda fake it in
                 # some cases, but it screws up the checking here for parsed XML
                 return True
-            if self.os.machine and self.os.machine != domcaps.machine:
+            if self.os.machine and not _compare_machine(domcaps):
                 return False
             if self.type and self.type != domcaps.domain:
                 return False
~~~

Before, we'd compare `self.os.machine` against `domcaps.machine`.

After, in accordance with the commit message, we continue performing the same comparison, but if it fails, we also rely on the information returned by `lookup_capsinfo`, for alias resolution. I see two problems with that:

* We call `lookup_capsinfo` even before we are sure that we need it. Namely, if the new comparison `self.os.machine == domcaps.machine` succeeds, we will have called `lookup_capsinfo` superfluously -- we just return `True`, and don't consume the `capsinfo` variable. Therefore if `lookup_capsinfo` were to throw an exception, then that exception would be unjustified in the first place -- we shouldn't even have reached that call.
* Let's assume we pushed down the `lookup_capsinfo` call, after the new `self.os.machine == domcaps.machine` comparison (I'm going to test this BTW), yet the call were *still* reached, and the exception were *still* thrown. How should we deal with that then? Well, the point of commit 05fcc7410eee was to "fix caching of domain capabilities"; in other words, if we just *suppress* the exception and return `False` from `_compare_machine`, it'll *only* mean that we need to regenerate the domcaps cache. That should be totally fine: we *couldn't determine* whether the selected machine type for the guest was or was not an alias, so we'll safely assume that it wasn't, and regenerate the domcaps cache.

**Comment by lersek** [comment] 2023-08-26 10:57
The root cause is that `lookup_capsinfo` (and `guest_lookup` called by it) are simply unusable for alias checking (or for anything else) if the domain in question uses an emulator that *differs* from the system default emulator. The information returned by `virConnectGetCapabilities()` pertains to the system default emulator.

**Comment by lersek** [comment] 2023-08-26 11:01
The following patch indeed suffices to fix the symptom (see the first bullet in my comment at https://github.com/virt-manager/virt-manager/issues/539#issuecomment-1694256206):

~~~
diff --git a/virtinst/guest.py b/virtinst/guest.py
index 123abfb242d8..9232405bb7c0 100644
--- a/virtinst/guest.py
+++ b/virtinst/guest.py
@@ -630,9 +630,9 @@ class Guest(XMLBuilder):
 
     def lookup_domcaps(self):
         def _compare_machine(domcaps):
-            capsinfo = self.lookup_capsinfo()
             if self.os.machine == domcaps.machine:
                 return True
+            capsinfo = self.lookup_capsinfo()
             if capsinfo.is_machine_alias(self.os.machine, domcaps.machine):
                 return True
             return False
~~~

I'm going to submit a pull request soon.

**Closed** 2023-08-29 11:24 UTC
